---
title: "problem2_hw4"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
```

```{r, message = FALSE}
library(tidyverse)
library(p8105.datasets)
library(plotly)
data("instacart")
```

Column {data-width=550}
-----------------------------------------------------------------------

### Chart A

```{r}
aisle_counts = 
  instacart |>
  count(aisle) |>
  filter(n > 10000) |>
  mutate(aisle = fct_reorder(aisle, n))

plot_ly(
  data = aisle_counts,
  x = ~n,
  y = ~aisle,
  type = "bar",
  orientation = "h"
  ) |> 
  layout(
  title = "Number of Items Ordered in Each Aisle (>10,000)",
  xaxis = list(title = "Number of Items Ordered"),
  yaxis = list(title = "Aisle")
  )
```

Column {data-width=550}
-----------------------------------------------------------------------

### Chart B

```{r}
orders_by_time = instacart  |> 
  mutate(order_dow = recode(order_dow,
                            `0` = "Sunday",
                            `1` = "Monday",
                            `2` = "Tuesday",
                            `3` = "Wednesday",
                            `4` = "Thursday",
                            `5` = "Friday",
                            `6` = "Saturday")) |> 
  group_by(order_dow, order_hour_of_day)|> 
  summarize(order_count = n(), .groups = "drop")

plot_ly(
  data = orders_by_time,
  x = ~order_hour_of_day,
  y = ~order_count,
  color = ~as.factor(order_dow),
  type = "scatter",
  mode = "lines+markers"
  ) |> 
  layout(
  title = "Orders by Hour and Day of Week",
  xaxis = list(title = "Hour of Day"),
  yaxis = list(title = "Number of Orders"),
  legend = list(title = list(text = "Day of Week"))
  )

```


### Chart C

```{r}
department_share = 
  instacart |> 
  count(department)

plot_ly(
  data = department_share,
  labels = ~department,
  values = ~n,
  type = "pie",
  textinfo = "label+percent",
  textposition = "inside"
) |> 
  layout(
    title = "Share of Orders by Department (Top 10)"
  )
```













To go back to the [homepage](index.html)